create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list PSxB.ZynqxI/PlatformxB.ScalpZynqPSxI/sys_clock/inst/clk_125]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {PLxB.ScalpClpxNumRegsxI/ReadStatexD[0]} {PLxB.ScalpClpxNumRegsxI/ReadStatexD[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][0]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][1]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][2]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][3]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][4]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][5]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][6]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][7]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][8]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][9]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][10]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][11]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][12]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][13]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][14]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][15]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][16]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][17]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][18]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][19]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][20]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][21]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][22]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][23]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][24]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][25]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][26]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][27]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][28]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][29]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][30]} {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdAddrxD][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][0]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][1]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][2]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][3]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][4]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][5]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][6]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][7]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][8]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][9]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][10]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][11]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][12]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][13]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][14]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][15]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][16]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][17]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][18]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][19]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][20]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][21]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][22]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][23]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][24]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][25]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][26]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][27]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][28]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][29]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][30]} {PLxB.ScalpClpxNumRegsxI/ReadS2MRegPortxD[RdDataxD][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][0]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][1]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][2]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][3]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][4]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][5]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][6]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][7]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][8]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][9]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][10]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][11]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][12]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][13]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][14]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][15]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][16]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][17]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][18]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][19]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][20]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][21]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][22]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][23]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][24]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][25]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][26]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][27]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][28]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][29]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][30]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARAddrxD][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][0]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][1]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][2]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][3]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][4]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][5]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][6]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][7]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][8]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][9]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][10]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][11]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][12]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][13]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][14]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][15]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][16]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][17]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][18]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][19]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][20]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][21]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][22]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][23]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][24]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][25]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][26]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][27]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][28]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][29]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][30]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RDataxD][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 2 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RRespxD][0]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RRespxD][1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][0]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][1]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][2]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][3]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][4]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][5]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][6]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][7]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][8]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][9]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][10]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][11]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][12]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][13]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][14]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][15]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][16]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][17]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][18]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][19]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][20]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][21]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][22]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][23]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][24]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][25]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][26]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][27]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][28]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][29]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][30]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWAddrxD][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 4 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WStrbxD][0]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WStrbxD][1]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WStrbxD][2]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WStrbxD][3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][0]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][1]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][2]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][3]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][4]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][5]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][6]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][7]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][8]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][9]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][10]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][11]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][12]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][13]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][14]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][15]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][16]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][17]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][18]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][19]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][20]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][21]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][22]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][23]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][24]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][25]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][26]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][27]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][28]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][29]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][30]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WDataxD][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][0]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][1]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][2]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][3]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][4]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][5]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][6]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][7]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][8]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][9]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][10]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][11]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][12]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][13]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][14]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][15]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][16]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][17]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][18]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][19]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][20]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][21]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][22]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][23]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][24]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][25]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][26]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][27]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][28]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][29]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][30]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrDataxD][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 4 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrStrbxD][0]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrStrbxD][1]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrStrbxD][2]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrStrbxD][3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 2 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][RespxD][S2MxD][BRespxD][0]} {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][RespxD][S2MxD][BRespxD][1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][0]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][1]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][2]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][3]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][4]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][5]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][6]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][7]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][8]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][9]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][10]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][11]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][12]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][13]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][14]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][15]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][16]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][17]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][18]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][19]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][20]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][21]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][22]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][23]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][24]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][25]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][26]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][27]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][28]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][29]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][30]} {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrAddrxD][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 2 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {PLxB.ScalpClpxNumRegsxI/WriteStatexD[0]} {PLxB.ScalpClpxNumRegsxI/WriteStatexD[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][M2SxD][ARValidxS]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][AddrxD][S2MxD][ARReadyxS]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][M2SxD][RReadyxS]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[RdxD][DataxD][S2MxD][RValidxS]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][M2SxD][AWValidxS]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][AddrxD][S2MxD][AWReadyxS]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][M2SxD][WValidxS]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][DataxD][S2MxD][WReadyxS]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][RespxD][M2SxD][BReadyxS]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {PLxB.ScalpClpxNumRegsxI/AxiSlvxD[WrxD][RespxD][S2MxD][BValidxS]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {PLxB.ScalpClpxNumRegsxI/ReadM2SRegPortxD[RdValidxS]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {PLxB.ScalpClpxNumRegsxI/WriteM2SRegPortxD[WrValidxS]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets ClpxNumRegsAxixD[ClockxC][ClkxC]]
